# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, dev_ada]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.x]
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        env:
          ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
          ACCESSKEYSECRET: ${{ secrets.ACCESSKEYSECRET }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm run deploy
      # - run: npm run ci
      # - name: build
      #   run: npm run build
      # - name: deploy
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: |
      #     npm run oss-push accessKeyId=$ACCESSKEYID accessKeySecret=$ACCESSKEYSECRET
